### ISSUE TITLE
RSS feed when using routes for blog

### ISSUE THREAD

**Issue by VoidMonk** [zutrinken/attila#143]
If I define a custom route (e.g. /blog) for the main collection, then the default RSS feed link of the theme breaks.

My routes.yaml includes:

```
routes:
collections:
  /blog/:
    permalink: /blog/{slug}/
    template: index
```

The RSS feed should be available at /blog/rss, but it still points to /rss as per the feed URL defined in `default.hbs` of theme set to `{{@site.url}}/rss/`.

Is it possible to make the RSS feed URL dynamic, based on the route? If not, then is there a workaround to change the feed URL?
