### ISSUE TITLE
Mode in the day, and the code segment color too shallow

### ISSUE THREAD

**Issue by rebron1900** [zutrinken/attila#223]
日间模式下，代码段颜色太浅

---
![image](https://user-images.githubusercontent.com/7929884/169255612-cca76dd2-2cf7-459a-8318-f294dda9e7f3.png)

样式表内给亮色主题更改颜色即可
```css
.theme-light .hljs{
    color:black;
}
```
